apiVersion: v1
kind: Namespace
metadata:
    name: sampleapp
    labels:
      name: sampleapp
# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: sampleapp-managed-csi
#   namespace: sampleapp
# provisioner: disk.csi.azure.com
# parameters:
#   skuName: StandardSSD_LRS  # available values: StandardSSD_LRS, StandardSSD_ZRS, Premium_LRS, Premium_ZRS, etc.
#   networkAccessPolicy: 'DenyAll'
#   publicNetworkAccess: 'Disabled'
#   resourceGroup: aks-adbmanaged-rg
# reclaimPolicy: Delete
# volumeBindingMode: WaitForFirstConsumer
# allowVolumeExpansion: true
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: sampleapp-pvc-azuredisk
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   # volumeName: sampleapp-pv-azuredisk
#   storageClassName: sampleapp-managed-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-front
  namespace: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-front
  template:
    metadata:
      labels:
        app: sample-front
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      securityContext:  # optional just to make sure user is non-root
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
      - name: sample-front
        image: s2c3lztst0909devseccr.azurecr.io/dotnet/samples:aspnetapp-chiseled-8.0
        # command:
        #   - "/bin/sh"
        #   - "-c"
        #   - echo $(date) >> /mnt/azuredisk/outfile; sleep 30; done
        # volumeMounts:
        # - name: azuredisk
        #   mountPath: "/mnt/azuredisk"
        #   readOnly: false
        ports:
        - containerPort: 8080
          name: sample-front
        # env:
        # - name: ASPNETCORE_HTTPS_PORTS
        #   value: "443;8081"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 8080
      # volumes:
      # - name: azuredisk
      #   persistentVolumeClaim:
      #     claimName: sampleapp-pvc-azuredisk
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: sample-svc
  namespace: sampleapp
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "s2c3lztst0909devsecsnet-aks-inbound"
    service.beta.kubernetes.io/azure-pls-create: "true"
    service.beta.kubernetes.io/azure-pls-name: "s2c3lztst0909devsecpls-sampleapp"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: sample-front
  ports:
  - port: 443
    targetPort: 8080
    protocol: TCP
    appProtocol: http

# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: allow-all-ingress
#   namespace: sampleapp
# spec:
#   podSelector: {}
#   ingress:
#   - {}
#   policyTypes:
#   - Ingress