# Build Name format
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
parameters:
  - name: AppName
    displayName: 'App Name'
    type: string
    default: 's2cccscne30909devseclogic'

  - name: ServiceConnectionName
    displayName: 'Service Connection Name'
    type: string
    default: 'SC-AM-CCC-ENV24508'

  - name: environmentId
    displayName: 'Environment Id'
    type: string
    default: 'ENV24508'

variables:
  AgentPool: CPP-Ubuntu2204-Preview
  BuildConfiguration: 'Release'
  PublishProject: 'datarelay.csproj'
  SolutionRootFolder: 'scenario3'
  BranchName: '1520'
  AdoProjectName: 'S02-App-AM-CCC'
  AppSettings: >
    -AzureBlob_blobStorageEndpoint "https://s2cccscne30909devsecsta.blob.core.windows.net/"
    -azureTables_tableStorageEndpoint "https://s2cccscne30909devsecsta.table.core.windows.net/"
    -DataRelay:StorageAccountName "s2cccscne30909devsecsta"
    -DataRelay:ContainerName "logicapp"

resources:
  repositories:
  - repository: templates
    type: git
    name: DRCP-Templates/templates
    ref: 'refs/heads/main'

trigger: none

pool: CPP-Ubuntu2204-Preview

extends:
  template: mandatory-template.yml@templates
  parameters:
    customerEnvironmentId: ${{parameters.environmentId}}
    pipelineStages:
    - stage: buildDeplyApplication
      displayName: 'Build and Deploy application'
      pool:
        name: ${{variables.AgentPool}}
      jobs:
      - template: /scenario2/application/Pipelines/PipelineTemplates/jobs/BuildPublishZipArtifact.yaml@self
        parameters:
          BuildConfiguration: ${{variables.BuildConfiguration}}
          PublishProject: ${{variables.PublishProject}}
          SolutionRootPath: '$(Build.SourcesDirectory)/${{variables.SolutionRootFolder}}'
      - template: scenario2/application/Pipelines/PipelineTemplates/jobs/DeployFunctionApp.yaml@self
        parameters:
          AppName: ${{parameters.AppName}}
          AppSettings: ${{variables.AppSettings}}
          BranchName: ${{variables.BranchName}}
          ProjectName: ${{variables.AdoProjectName}}
          ServiceConnectionName: ${{parameters.ServiceConnectionName}}
          SolutionName: 'datarelay'
          DependsOn: 'Build_Publish_Zip_Artifact'