parameters:
  AppName: ''
  AppSettings: ''
  BranchName: ''
  ProjectName: ''
  ServiceConnectionName: ''
  SolutionName: ''
  DependsOn: []

jobs:
  - job: 'Deploy_${{parameters.SolutionName}}_FunctionApp'
    dependsOn: ${{parameters.DependsOn}}
    steps:
      - checkout: none

      - task: DownloadBuildArtifacts@0
        displayName: 'Download ${{parameters.SolutionName}} Artifact'
        inputs:
          buildType: current
          project: ${{parameters.ProjectName}}
          buildVersionToDownload: latestFromBranch
          branchName: '${{parameters.BranchName}}'
          downloadType: single
          artifactName: 'drop'
          downloadPath: '$(Pipeline.Workspace)/_Build ${{parameters.SolutionName}}'

      - task: AzureFunctionApp@1
        displayName: 'Deploy ${{parameters.SolutionName}} Function App'
        inputs:
          azureSubscription: '${{parameters.ServiceConnectionName}}'
          appType: functionApp
          appName: '${{parameters.AppName}}'
          package: '$(Pipeline.Workspace)/_Build ${{parameters.SolutionName}}/drop/Release/${{parameters.SolutionName}}.zip'
          appSettings: ${{parameters.AppSettings}}
